#!/usr/bin/env ruby

# fiflist - Find In Files List Lines
# this script iterates over each file returned by `fif`
#     and displays each matching line


SEARCH_PATH     = ARGV[0]
SEARCH_TERM     = ARGV[1]
EXCLUDE_TERM    = ARGV[2]
COINCIDENT_TERM = ARGV[3]
USAGE           = "USAGE:\n"                                                                            +
                  "\tfiflist <path/to/search> <search-term> [ <exclude-term> ] [ <coincident-term> ]\n" +
                  "DESCRIPTION:\n"                                                                      +
                  "\tfind search-term in files displaying each matching line\n"


unless SEARCH_TERM ; print USAGE ; exit ; end ;

fif_cmd  = "fif \"#{SEARCH_PATH}\" \"#{SEARCH_TERM}\" \"#{EXCLUDE_TERM}\""
fif_list = `#{fif_cmd}`.split "\n"

fif_list.each do |ea|
  print "\n#{ea}\n"
  system "cat #{ea} | grep -n \"#{SEARCH_TERM}\""
  system "cat #{ea} | grep -n \"#{COINCIDENT_TERM}\"" unless COINCIDENT_TERM.nil?
end
