#!/bin/bash

readonly SHOW_DIFFS=$( [[ "$1" == '-d' ]] ; echo $(( ! $? )) ) ; (( SHOW_DIFFS )) && shift ;
readonly BRANCH=$(     [[ -n "$1"      ]] && echo $1 || echo '*' )
readonly BRANCHES=( $( git branch --list "${BRANCH}" | grep -v master | sed 's|^\* |  |' ) )



gitcommonancestor() # ([-s] ref_a ref_b)
{
  local is_short=$( [[ "$1" == '-s' ]] ; echo $(( ! $? )) ) ; (( is_short )) && shift ;
  local fmt=$(      (( is_short     )) && echo "%h" || echo "%h %ad %an [%G?] %s %d" )
  local ref_a=$1
  local ref_b=$(    [[ -n "$2"      ]] && echo $2 || echo HEAD )

  [[ -n "${ref_a}" ]] || ! echo "no ref specified" || return 1

  git log -n1 --format="${fmt}" --date=short $(git merge-base ${ref_a} ${ref_b})
}

main()
{
  local branch
  local common_ancestor
  local changed_files

  for branch in ${BRANCHES[*]}
  do  common_ancestor=$(gitcommonancestor -s master ${branch})
      changed_files=( $(git diff --name-only ${common_ancestor} ${branch}) )

      if   (( SHOW_DIFFS ))
      then git diff ${common_ancestor} ${branch}
      else echo '---' ; printf "[${branch}]: %s\n" "${changed_files[@]}"
      fi
  done
}


if   (( SHOW_DIFFS ))
then main "$@"
else main "$@" | column -t
fi
