#!/bin/bash

# IF='eth0'
IF=`ls /sys/class/net/ | grep -E '^wl'`
IVL=3
KB_SCALE=$(($IVL*125)) # bytes => kbits
UP_STATS_FILE=/sys/class/net/$IF/statistics/tx_bytes
DOWN_STATS_FILE=/sys/class/net/$IF/statistics/rx_bytes
if   [ "$1" == "--up" ]
then DIR="up"   ; STATS_FILE=$UP_STATS_FILE
else DIR="down" ; STATS_FILE=$DOWN_STATS_FILE
fi


total_bytes=`cat $STATS_FILE`
prev_bytes=$total_bytes

while ((1))
do    total_bytes=`cat $STATS_FILE`
      bytes=$(($total_bytes-$prev_bytes))
      kbps=$(($bytes/$KB_SCALE))
      prev_bytes=$total_bytes

      [ $(($kbps)) -gt $((99)) ] && spd-say "$(($kbps/100*100)) k" || spd-say "$kbps k"
      clear ; echo "$((bytes/$IVL)) bytes/sec $DIR" ;
              echo "$((kbps*1000 )) bits/sec  $DIR" ;
      sleep $IVL
done
