#!/bin/bash


ALSA_CAPTURE_CARD_N=$1
CAPTURE_PIN='Capture,0'
CAPTURE_STATE_ON='100% cap'
CAPTURE_STATE_OFF='0% nocap'
INPUT_PIN='Rear Mic'
MIC_BOOST_PIN='Rear Mic Boost,0'
MIC_BOOST_VAL='30.00dB'
LED_STATE_ON='-led'
LED_STATE_OFF='led'
TOGGLE_STATE_ON='1'
TOGGLE_STATE_OFF='0'
CAPTURE_STATE="$CAPTURE_STATE_OFF"
LED_STATE="$LED_STATE_OFF"
TOGGLE_STATE="$TOGGLE_STATE_OFF"
STATE_FILE=mic-toggle-state

[ $1 ] || ((speaker-test -t sine -f 1000)& pid=$! ; sleep 0.1s ; kill -9 $pid ; exit ;)


if ((`cat $STATE_FILE`))
then CAPTURE_STATE="$CAPTURE_STATE_OFF" LED_STATE="$LED_STATE_OFF" TOGGLE_STATE="$TOGGLE_STATE_OFF"
else CAPTURE_STATE="$CAPTURE_STATE_ON"  LED_STATE="$LED_STATE_ON"  TOGGLE_STATE="$TOGGLE_STATE_ON"
fi
amixer -c $ALSA_CAPTURE_CARD_N sset $CAPTURE_PIN $CAPTURE_STATE
amixer -c $ALSA_CAPTURE_CARD_N sset 'Input Source' "$INPUT_PIN"
amixer -c $ALSA_CAPTURE_CARD_N sset "$MIC_BOOST_PIN" "$MIC_BOOST_VAL"
xset "$LED_STATE" named 'Scroll Lock'
echo "$TOGGLE_STATE" > $STATE_FILE


# echo "cat STATE_FILE=`cat $STATE_FILE` CAPTURE_STATE=$CAPTURE_STATE LED_STATE=$LED_STATE TOGGLE_STATE=$TOGGLE_STATE"
