#!/bin/bash

read -r -d '' USAGE <<-'USAGE_END'
USAGE:

        vm [ -h | --help | <img> | <img-dir> | -l | --list | <n> ]

    where: <img> is the path to an .img file
    where: <img-dir> is one of `ls -d $VM_DIR/*/`
    where: <n> is one of the numbered selections of `vm --list`


ENVIRONMENT:

    * VM_DIR       - (mandatory) full path to parent directory of VM subdirectories
    * ARCH         - (optional)  launches qemu-system-$ARCH (default: 'x86_64 + kvm + smp')
    * MEM          - (optional)  specifies VM memory size (default: 1G)
    * ISO          - (optional)  .iso file for first optical disc - set as primary boot media (default: none)
    * IMG_B        - (optional)  .img file for second hard disk (default: none)
    * SMP          - (optional)  SMP options as CSV: N_CORES,N_THREADS,N_SOCKETS (default: 2,1,1)
    * VM_SSH_PORT  - (optional)  external port to bind to internal port tcp/22
    * VM_HTTP_PORT - (optional)  external port to bind to internal port tcp/80
    * VM_SSH_LOGIN - (optional)  internal ssh user to login (if VM_SSH_PORT and VM_WAIT_SSH defined)
    * VM_WAIT_SSH  - (optional)  pause before ssh login (if VM_SSH_PORT and VM_SSH_LOGIN defined)


EXAMPLES:

    vm                     # present a alphabetical list of VMs and wait for choice
    vm /home/me/vm.img     # launch a VM by absolute or relative path to an image file
    vm img-dir             # launch $VM_DIR/img-dir/img-dir.img if it exists
    vm -h (or --help)      # present this message then quit
    vm -l (or --list)      # present a alphabetical list of VMs then quit
    vm 1                   # launch a VM by it's current order number from `vm --list`
    ARCH=i386          vm  # launch 32-bit x86 VM
    MEM=1G             vm  # launch VM using 1GB of system memory
    ISO=/path/to/iso   vm  # boot from .iso file
    IMG_B=/path/to/img vm  # mount second hard disk
    VM_SSH_PORT=       vm  # do not forward ssh
    VM_HTTP_PORT=      vm  # do not forward http
    VM_SSH_LOGIN=      vm  # forward ssh but do not login
    VM_WAIT_SSH=60     vm  # wait N seconds to login
USAGE_END
readonly HAS_LIST_SWITCH=$([ "$1" == "-l" -o "$1" == "--list" ] && echo 1 || echo 0)
readonly HAS_HELP_SWITCH=$([ "$1" == "-h" -o "$1" == "--help" ] && echo 1 || echo 0)
readonly IMG_NAME_OR_N=$1                                          # pending validation
readonly IMG_FULL_PATH="$VM_DIR/$IMG_NAME_OR_N/$IMG_NAME_OR_N.img" # pending validation
readonly VM_DIR_NULL_ERR_MSG="VM_DIR must be defined in the environment"
readonly VM_DIR_MISSING_ERR_MSG="VM_DIR not found: '$VM_DIR'"
readonly ISOS_DIR_NAME="isos"
readonly SCRATCH_IMG_NAME="scratch"
readonly ISOS_DIR=$VM_DIR/$ISOS_DIR_NAME
readonly SCRATCH_IMG_DIR=$VM_DIR/$SCRATCH_IMG_NAME
readonly SCRATCH_IMG=$SCRATCH_IMG_DIR/$SCRATCH_IMG_NAME.img
readonly HAS_SCRATCH_IMG=$(
  [[ -d "$SCRATCH_IMG_DIR/" ]] || mkdir -p "$SCRATCH_IMG_DIR" 1>&2
  [[ -f "$SCRATCH_IMG"      ]] || qemu-img create "$SCRATCH_IMG" 9G 1>&2 && echo 1 || echo 0
)
declare -r -a ISOS=( $(
  [[ -d "$ISOS_DIR/" ]] || mkdir -p "$ISOS_DIR"

  find $ISOS_DIR/ -name *.iso 2> /dev/null
) )
declare -r -a IMG_DIRS=( $(
  (( $HAS_SCRATCH_IMG )) && echo $SCRATCH_IMG_NAME

  for img_full_path in $(ls -d $VM_DIR/*/*.img 2> /dev/null)
  do  dir=$(basename $(dirname $img_full_path))
      img=$(basename $img_full_path)
      [[ "$dir" == "$SCRATCH_IMG_NAME" ]] && continue

      grep "^$dir\.img$" <<<$img > /dev/null && echo $dir
  done
) )
readonly N_IMGS=${#IMG_DIRS[@]}
readonly N_ISOS=${#ISOS[@]}
readonly SMP_REGEX="^[0-9],[0-9],[0-9]$"
readonly USE_VIRTIO=0
readonly USE_VIRTFS=0
readonly USE_VIRTSMB=0

ImgDir=        # deferred
OverridesFile= # deferred
Img=           # deferred
Iso=           # deferred


function doesImgExist { [[ -f "$1" ]] && [[ "$(grep -E '^.+\.img$' <<<$1)" == "$1" ]] ; }

function doesIsoExist { [[ -f "$1" ]] && [[ "$(grep -E '^.+\.iso$' <<<$1)" == "$1" ]] ; }

function isInteger { [[ "$1" =~ ^([0-9]+)$ ]] ; }

function isValidSelection # (option_n , n_options)
{
  local option_n=$( isInteger $1 && echo $1 || echo '-1')
  local n_options=$(isInteger $2 && echo $2 || echo '0' )

  [[ "$option_n" -ge "0" ]] && [[ "$option_n" -le "$n_options" ]]
}

PrintImgOptions()
{
  for img_dir_n in "${!IMG_DIRS[@]}" ; do echo "$(( $img_dir_n+1 ))) ${IMG_DIRS[$img_dir_n]}" ; done ;
}

PrintIsoOptions()
{
  for iso_n in "${!ISOS[@]}" ; do echo "$(( $iso_n + 1 ))) ${ISOS[$iso_n]##*/}" ; done ;
}

function selectImage # (img_n)
{
  local img_n=$1
  local img_selection=$(isValidSelection $img_n $N_IMGS && echo $img_n || echo '-1')

  if   (( $N_IMGS > 0 ))
  then until isValidSelection $img_selection $N_IMGS
       do    echo -e "Select a primary disk:\n" ; PrintImgOptions ;
             echo -en "\nChoice (1$( (( $N_IMGS > 1 )) && echo "-$N_IMGS"), 0=quit): "
             read img_selection ; [[ "$img_selection" == '0' ]] && exit

             if ! isValidSelection $img_selection $N_IMGS
             then clear ; echo "Selection ($img_selection) out of range" ;
             fi
       done
  else echo "no conventionally-named images found in \$VM_DIR '$VM_DIR/'"
       exit 1
  fi

  ImgDir=${IMG_DIRS[$(( $img_selection - 1 ))]}
  OverridesFile=$VM_DIR/$ImgDir/vm-config
  Img=$VM_DIR/$ImgDir/$ImgDir.img
}

function selectIso
{
  local iso_selection='-1'

  if (( $N_ISOS > 0 ))
  then until isValidSelection $iso_selection $N_ISOS
       do    echo -e "Select a boot ISO:\n" ; PrintIsoOptions ;
             echo -en "\nChoice (1$( (( $N_ISOS > 1 )) && echo "-$N_ISOS"), 0=quit): "
             read iso_selection ; [[ "$iso_selection" == '0' ]] && exit

             if ! isValidSelection $iso_selection $N_ISOS
             then clear ; echo "Selection ($iso_selection) out of range" ;
             fi
       done
  else echo "no ISOs found in \$ISOS_DIR: '$ISOS_DIR/'"
       exit 1
  fi

  Iso=${ISOS[$(( $iso_selection - 1 ))]}
}

function waitSsh
{
  ssh-keygen -f "~/.ssh/known_hosts" -R [localhost]:$VM_SSH_PORT
  while (( $WAIT_SSH > 0 ))
  do    WAIT_SSH=($WAIT_SSH-1)
        clear ; echo "logging in ssh in $(($WAIT_SSH+1)) seconds" ;
        sleep 1
  done
}


## main entry ##

(( $HAS_LIST_SWITCH )) && PrintImgOptions                && exit
(( $HAS_HELP_SWITCH )) && echo "$USAGE"                  && exit
[[   -z "$VM_DIR"   ]] && echo "$VM_DIR_NULL_ERR_MSG"    && exit
[[ ! -d "$VM_DIR"   ]] && echo "$VM_DIR_MISSING_ERR_MSG" && exit

# determine which VM image to launch
if   [[ -n "$IMG_NAME_OR_N" ]]
then if ! isInteger $IMG_NAME_OR_N
     then # find image by img name
          for img in "$IMG_NAME_OR_N" "$IMG_FULL_PATH" ; do doesImgExist $img && Img=$img ; done ;
          [[ "$Img" ]]                            || echo "\$Img not found at '$IMG_NAME_OR_N' or '$IMG_FULL_PATH'"
     else isValidSelection $IMG_NAME_OR_N $N_IMGS || echo "\$Selection ($IMG_NAME_OR_N) out of range"
     fi
fi
[[ -z "$ISO" ]] || doesIsoExist "$ISO" || echo "\$ISO not found at: '$ISO'"
until doesImgExist $Img
do    # find image by img_n
      selectImage $IMG_NAME_OR_N ; clear ;
done

# determine which ISO to boot
if   doesIsoExist "$ISO"
then Iso="$ISO"
elif [[ "$ImgDir" == "$SCRATCH_IMG_NAME" ]]
then until doesIsoExist "$Iso" ; do selectIso ; clear ; done ;
fi

echo -e "Selected:\n\tIso: $Iso\n\tImg: $Img"


# prepare the environment
[[ -f $OverridesFile    ]] && source $OverridesFile
[[ "$SMP" =~ $SMP_REGEX ]] && N_CORES=${BASH_REMATCH[1]} N_THREADS=${BASH_REMATCH[2]} N_SOCKETS=${BASH_REMATCH[3]} || \
                              N_CORES=2                  N_THREADS=1                  N_SOCKETS=1
[[ -z "$ARCH"           ]] && ARCH="x86_64"
[[ "$ARCH" == 'x86_64'  ]] && CPU="-cpu host -smp cores=$N_CORES,threads=$N_THREADS,sockets=$N_SOCKETS"
[[ "$ARCH" == 'x86_64'  ]] && ARCH="x86_64 -enable-kvm"
[[ "$ImgDir"            ]] && NAME="-name $ImgDir"
[[ "$IMG_B"             ]] && HD="-drive file=$IMG_B,format=raw,cache=writeback"
doesIsoExist "$Iso"        && CD="-cdrom $Iso" BOOT="-boot order=d"                 || CD="" BOOT=""
[[ "$MEM"               ]] && MEM="-m $MEM"                                         || MEM="-m 1G"
[[ "$VGA"               ]] && VGA="-vga $VGA"                                       || VGA="-vga std" # cirrus, qxl, std, vmware
[[ "$VM_SSH_PORT"       ]] && FWD_SSH=",hostfwd=tcp::$VM_SSH_PORT-:22"              || FWD_SSH=''
[[ "$VM_HTTP_PORT"      ]] && FWD_HTTP=",hostfwd=tcp::$VM_HTTP_PORT-:$VM_HTTP_PORT" || FWD_HTTP=''
QEMU="qemu-system-$ARCH $NAME"
HD="-drive file=$Img,format=raw,cache=writeback $HD"
# BOOT="-boot menu=on"

# prepare networking
SHARED_DIR_DEFAULT=$HOME/.config/vm-shared
[[ ! -d "$SHARED_DIR" ]] && [[ -d "$SHARED_DIR_DEFAULT" ]] && SHARED_DIR=$SHARED_DIR_DEFAULT
NET_VIRTIO="-netdev user,id=vmnic$FWD_SSH$FWD_HTTP -device virtio-net,netdev=vmnic"
NET_VIRTSMB="-net user,smb=\"$SHARED_DIR\" -net nic,model=virtio"
NET_VIRTFS="-virtfs local,path=\"$SHARED_DIR\",mount_tag=host0,security_model=passthrough,id=host0"
#     (( $USE_VIRTIO )) && NET="$NET_VIRTIO" || NET=''
if   ((   $USE_VIRTIO ))
then NET="$NET_VIRTIO"
elif ((   $USE_VIRTSMB ))
then NET="$NET_VIRTSMB"
elif ((   $USE_VIRTFS ))
then NET="$NET_VIRTFS" # guest fstab entry: host0 /a-mountpoint 9p trans=virtio,version=9p2000.L 0 0
else NET=''
fi

# prepare SSH
SSH="ssh -o StrictHostKeyChecking=no -p $VM_SSH_PORT $VM_SSH_LOGIN@localhost"
# SSH="-redir tcp:$VM_SSH_PORT::22" # no virtio - deprecated
[[ "$VM_SSH_PORT" ]] || [[ "$VM_HTTP_PORT"    ]] || NET=''
[[ "$VM_SSH_PORT" ]] && [[ "$VM_SSH_LOGIN"    ]] || SSH=''
[[ "`echo $VM_WAIT_SSH | grep -E '^[1-9]+$'`" ]] || WAIT_SSH=30

# prepare A/V
AUDIO="-soundhw hda"
#VIDEO_SDL="-display sdl -no-frame"
VIDEO_SDL="-display sdl"
VIDEO_VNC="-display vnc=:0"
VIDEO="$VIDEO_SDL"
MISC="-show-cursor"


# load virtio kernel modules
if   (( $USE_VIRTIO ))
then virtio_modules=`lsmod | grep virtio`
     [[ "`echo $virtio_modules | grep virtio_net`"    == "" ]] && su -c 'modprobe virtio-net'
     #[[ "`echo $virtio_modules | grep virtio_blk`"     == "" ]] && su -c 'modprobe virtio-blk'
     #[[ "`echo $virtio_modules | grep virtio_scsi`"    == "" ]] && su -c 'modprobe virtio-scsi'
     #[[ "`echo $virtio_modules | grep virtio_serial`"  == "" ]] && su -c 'modprobe virtio-serial'
     #[[ "`echo $virtio_modules | grep virtio_balloon`" == "" ]] && su -c 'modprobe virtio-balloon'
fi

# concatenate command line and report
echo "launching vm: '`echo "$Img" | grep -E '^.+\.img$' | sed -e 's/^\(.*\/\)\?\(.*\).img$/\2/'`'"
CMD="$QEMU $CPU $MEM $HD $CD $BOOT $VGA $NET $AUDIO $VIDEO $MISC"
echo "$CMD"

# launch VM and optionally login ssh
[[ "$FWD_SSH"  ]] && echo "SSH port 22 forwarded to localhost:$VM_SSH_PORT"
[[ "$FWD_HTTP" ]] && echo "HTTP port $VM_HTTP_PORT forwarded to localhost:$VM_HTTP_PORT"
if   [[ "$SSH" ]] && [[ "$WAIT_SSH" ]]
then $CMD & waitSsh && $SSH
else $CMD
fi
